# Generated by Django 3.2.3 on 2021-05-18 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20210518_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='size',
            field=models.TextField(default='', help_text='Enter notes regarding what size you need', max_length=1000),
        ),
    ]
