# Generated by Django 3.2.3 on 2021-05-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20210518_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='size',
            field=models.CharField(default='', help_text='Enter notes regarding what colour you want', max_length=400),
        ),
    ]
