# Generated by Django 3.2.3 on 2021-05-18 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_gift_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='colour',
            field=models.CharField(default='', help_text='Enter notes regarding what colour you want', max_length=400),
        ),
        migrations.AlterField(
            model_name='gift',
            name='size',
            field=models.TextField(default='', help_text='Enter notes regarding what size you need', max_length=1000),
        ),
    ]
