# Generated by Django 3.2.3 on 2021-05-18 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20210518_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giftinstance',
            name='price',
        ),
        migrations.RemoveField(
            model_name='giftinstance',
            name='size',
        ),
        migrations.RemoveField(
            model_name='giftinstance',
            name='url',
        ),
    ]
