# Generated by Django 3.2.3 on 2021-05-18 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20210518_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftinstance',
            name='colour',
            field=models.CharField(default='', help_text='Enter notes regarding what colour you want', max_length=400),
        ),
        migrations.AddField(
            model_name='giftinstance',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='giftinstance',
            name='size',
            field=models.TextField(default='', help_text='Enter notes regarding what size you need', max_length=1000),
        ),
        migrations.AddField(
            model_name='giftinstance',
            name='url',
            field=models.URLField(default='', help_text='enter a link which might help your buyer'),
        ),
    ]
