# Generated by Django 3.2.3 on 2021-05-18 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20210518_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gift',
            name='colour',
        ),
        migrations.RemoveField(
            model_name='gift',
            name='price',
        ),
        migrations.RemoveField(
            model_name='gift',
            name='size',
        ),
        migrations.RemoveField(
            model_name='gift',
            name='url',
        ),
    ]
