# Generated by Django 3.2.4 on 2021-07-19 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_alter_country_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(help_text='Enter the country the gift was made in', max_length=200, unique=True),
        ),
    ]
