# Generated by Django 3.2.4 on 2021-07-19 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_alter_country_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Enter a gift category (e.g. electronics or clothes)', max_length=200, unique=True),
        ),
    ]
