# Generated by Django 3.2.4 on 2021-07-19 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_alter_category_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
    ]
