# Generated by Django 3.2.4 on 2021-07-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_auto_20210720_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='category',
            field=models.ManyToManyField(blank=True, help_text='Select a category for this gift', to='catalog.Category'),
        ),
    ]
